/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#4f46e5',
          hover: '#4338ca',
          active: '#3730a3',
          soft: '#eef2ff',
          border: '#c7d2fe',
          dark: '#5f63e8',
          'hover-dark': '#5357d9',
          'active-dark': '#474ac4',
          'soft-dark': '#23233a',
          'border-dark': '#4c4f8f',
        },
        secondary: {
          DEFAULT: '#0891b2',
          hover: '#0e7490',
          soft: '#ecfeff',
          border: '#a5f3fc',
          dark: '#22a9c9',
          'hover-dark': '#2bb9dc',
          'soft-dark': '#16333b',
          'border-dark': '#245967',
          'button-dark': '#0e7490',
          'button-hover-dark': '#155e75',
        },
        success: {
          DEFAULT: '#059669',
          hover: '#047857',
          soft: '#ecfdf5',
          border: '#a7f3d0',
          dark: '#10b981',
          'hover-dark': '#34d399',
          'soft-dark': '#123528',
          'border-dark': '#1f6f55',
          'button-dark': '#047857',
          'button-hover-dark': '#065f46',
        },
        error: {
          DEFAULT: '#e11d48',
          hover: '#be123c',
          soft: '#fff1f2',
          border: '#fecdd3',
          dark: '#ff5d7d',
          'hover-dark': '#ff7a94',
          'soft-dark': '#3f1722',
          'border-dark': '#893244',
        },
        warning: {
          DEFAULT: '#d97706',
          hover: '#b45309',
          soft: '#fffbeb',
          border: '#fde68a',
          dark: '#f59e0b',
          'hover-dark': '#fbbf24',
          'soft-dark': '#3b2a11',
          'border-dark': '#7c5a1a',
        },
        background: {
          DEFAULT: '#f8fafc',
          dark: '#121212',
        },
        surface: {
          DEFAULT: '#ffffff',
          muted: '#f1f5f9',
          dark: '#242424',
          'muted-dark': '#2f2f2f',
        },
        border: {
          DEFAULT: '#e2e8f0',
          subtle: '#f1f5f9',
          strong: '#cbd5e1',
          dark: '#3a3a3a',
          'subtle-dark': '#2d2d2d',
          'strong-dark': '#525252',
        },
        text: {
          primary: '#0f172a',
          secondary: '#64748b',
          tertiary: '#94a3b8',
          'primary-dark': '#e8e8e8',
          'secondary-dark': '#a3a3a3',
          'tertiary-dark': '#737373',
        },
      },
      fontFamily: {
        sans: ['Manrope', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      transitionDuration: {
        app: '200ms',
        entrance: '300ms',
      },
      transitionTimingFunction: {
        app: 'cubic-bezier(0.2, 0.8, 0.2, 1)',
      },
      boxShadow: {
        sm: '0 10px 28px rgb(15 23 42 / 0.06)',
        md: '0 10px 28px rgb(15 23 42 / 0.06)',
        xl: '0 10px 28px rgb(15 23 42 / 0.06)',
      },
    },
  },
}
